### PR TITLE
File path in recent menu bar #247 

### PR DESCRIPTION
**Pull request by GiveMeCofee**
Added file path to project name in recent projects menu sub bar. 

filepath

P.S. Sorry if i did something wrong, this is my first contribution :(

### CODE REVIEW

**Comment by azakhary** [comment]
This looks cool, although it makes a HUGE menu bar :D I was thinking wouldn't it be better ig you show path when projects opened in title bar title? that would be more useful, as you need to know path usually when project is already opened.

**Comment by GiveMeCofee** [comment]
Yea sure, going to fix it, btw should i leave full path like this or cut the some of the beginning of the file path according to OS?

**Comment by azakhary** [comment]
I think full is good.

**Comment by johanessurya** [comment]
Wow it looks good. I think it isn't problem look huge, because it didn't annoy user. It just huge when user need it. 

Here recent project of notepad++, which is very usefull for me and it's huge too: 
npp-recent-project

It good if you add in title bar too like this(notepad++):
notepad-title-path

You could make like this:
Overlap2D - [Project Path]
OR
[Project Path] - Overlap2D

It doesn't matter for me. Both of two is very useful. :)

**Comment by GiveMeCofee** [comment]
So i updated the code so it would show the path in the title and for now left the code to show the path in the recent projects, as @johanessurya said it still might be usefull. 

titlepath

recentpath

**Comment by johanessurya** [comment]
Wow!
Looks great! :+1:

**Pull request merged**
