### PR TITLE
extended alignment functionality

### PR DESCRIPTION
**Pull request by kutoman**
- extended alignment functionality by center horizontally/vertically (relative to the broadest/highest item of the current selection)

- added git-ignored "local" directory

### CODE REVIEW

**Comment by azakhary** [comment]
Looks great, thank you.
I have also added the correct icons, to avoid "red" "yellow" thing.

Would be cool to later move alignment toolbox as a separate box.

**Comment by kutoman** [comment]
you're welcome :). In addition to what you've said, I also would like to add a checkbox whether to consider alignement as group. Thus the distances among the items in the group (according to the selection) would be kept.

**Comment by azakhary** [comment]
That could be a keypress. (for example if Ctrl is pressed consider them as group)

Another thing that would be cool to add, is align to parent. so that you can align item to it's parent composite (left, right, bottom, down, center e.g.)

That will require a whole new box though. Preferable made with VisUI contrary to way it's made now.

**Comment by azakhary** [comment]
In future we can even have a check box to make the alignment bindable, so that if item is aligned to right of it's parent composite, that is stored in it's VO as alignment type not a coordinate, meaning, if you change size of outer composite it will still always stick to it's right. That way we will have amazing UI components, that are flexible and resizable. (just a thought for the future)

**Comment by kutoman** [comment]
interesting ideas

**Pull request merged**
