### PR TITLE
Fix crash in SandboxMediator when currentSelectedTool is null #274

### PR DESCRIPTION
**Pull request by saltares**

### CODE REVIEW

**Comment by azakhary** [comment]
Thanks a lot! I'll check this out first thing tomorrow morning before merging.

**Comment by azakhary** [comment]
I always wanted to put this null checks, but every time I was wandering, how can current tool be null in the first place? I don't see an obvious scenario for this to happen. But I guess that's another topic and null checks are necessary in any case.

Thanks a lot!

**Comment by saltares** [comment]
> how can current tool be null in the first place?

I can see a few scenarios here:
* [Trying to set a tool with an invalid name](https://github.com/saltares/overlap2d/blob/02bb57a57dac922bc3b64e39672a5e38805145be/overlap2d/src/com/uwsoft/editor/view/stage/SandboxMediator.java#L97)
* [Any chance we could be passing `null` to the tool hotswap method?](https://github.com/saltares/overlap2d/blob/02bb57a57dac922bc3b64e39672a5e38805145be/overlap2d/src/com/uwsoft/editor/view/stage/SandboxMediator.java#L494)
* [Calling `toolHotswapBack` twice in a row would definitely do it](https://github.com/saltares/overlap2d/blob/02bb57a57dac922bc3b64e39672a5e38805145be/overlap2d/src/com/uwsoft/editor/view/stage/SandboxMediator.java#L499)

**Comment by azakhary** [comment]
right. true.. I think twice in a row hotswap is the actual candidate, I'll look into it.

**Pull request merged**
