### PR TITLE
#129 +adds rename layer feature (pending to add validator and filter)

### LINKED ISSUE #129: Ability to rename selected layer
Ability to rename selected layer

### PR DESCRIPTION
**Pull request by AlbertoCejas**
Fixes #129 

Adds rename layer feature with double click on the layer slot.

Code format/enconding doesn't seem to be the same so the whole file has been changed.
To make your life easier, I have just changed:
- UILayerBox -> UILayerItem
   * I have added the layer name as a TextField instead of a simple Label.
- uiSkin.json
   * I have added "transparent" style for TextFields

### CODE REVIEW

**Comment by azakhary** [comment]
Oh, awesome! I almost started working on thismyself today but didn't :D Good timing :) I'll pull it tomorrow, and merge then. Thanks!

**Comment by azakhary** [comment]
I pulled the brunch, in terms of looks it looks awesome.

But some things don't work:

1) when clicking putside renaming mode doesnot dissapear. Ideally if clicked somewhere else "lost focus" it should go back to being normal looking.
2) Mouse cursor. while on most of text fields we gorce text field cursor, on this one it should not happen untill doubleclicled
3) Pressing Enter, after done changing name of pressed enter, it should convert back to none diting mode.

Other note in terms of keeping the architecture standart.
As you noticed all our panels come with 2 classes, one for view and other for logic (the logic classes have Mediator word at the end)
view classes are not supposed to modify data, just fire notifications for mediator. (see delete layer as example)
So in this case ideal would be for when the enter is pressed or focus is list (read when naem change is done) for view to just fire notification something like
LAYER_NAME_CHANGED and pass new name in the body. then the mediator can lsiten for this event, and actually modify the data. 
This way in feature I can add this as a "command" so that it will be affected by Ctrl+Z.

Let me know if you can do this, or at least some of this changes before I can merge. 

Again, this looks very good, thank you!

**Comment by azakhary** [comment]
Oh Also one more thing, why in editing mode, it should not be "Draggable" so that you can do text selection without triggering drag reorder.

**Comment by AlbertoCejas** [comment]
Thanks for the feedback. I tried to do a quick PR so I wouldn't conflict with some other contributor. I will try to perform those changes asap. ;)

**Comment by azakhary** [comment]
don't worry for conflicts, I have already pulled your changes and resolved merging conflicts, so all will be ok ;)

**Comment by AlbertoCejas** [comment]
Hi again!! :)

After digging a little bit more into the project, I just added those improvements. Let me know if something doesn't adapt to the current arquitecture.

I don't know if it exists but it would be amazing for new contributors if the editor has a code arquitecture overview documentation elsewhere.

**Comment by azakhary** [comment]
Thanks! I'll be checking this first thing in the morning. I would love to sit down and make an architecture doc, but it takes time. If something is off, I'll fix it, don't worry!

**Comment by azakhary** [comment]
Merged, found some other bugs in layers but unrelated to this. Renaming part works perfect! And all is correct. in Future I might, modify it slightly to use Undo redoable command for renaming so that it becomes undo-able action. I did it several days ago for deleteing layer.

**Comment by azakhary** [comment]
Thanks a lot for helping us out!

**Pull request merged**
