### PR TITLE
Issue 351 follower size

### PR DESCRIPTION
**Pull request by skusku**
Fixed Problem where:
a) Follower for Composite Items did not fit the size of the content of the composite item (See BasicFollower.java)
b) Problem that was posed by the fix on BasicFollower.java, where scaling the composite item showed strange behaviour (See TransformTool.java)

### CODE REVIEW

**Comment by skusku** [comment]
You're right. I'll look into it when I get some spare time.

**Comment by skusku** [comment]
The problem I see fixing this is that I am basically not allowed to schedule recalculating the size of an object myself. 
CompositeSystem::recalculateSize() is part of an Ashley system.
Am I allowed to fetch a reference to an Ashley System from outside the Engine?
What would be the most elegant way to do this?
Could refactoring this function to a more openly available class be the better choice? The function itself is (so far) only called from CompositeSystem::processEntity() and you may see the problem that lies therein:

We have to wait for the engine to tick in order for the right size of our object to be calculated. Everything that happens before the engine update has the wrong boundingbox and width and height sizes ( if we are lucky and the bounding box even exists yet ).

Can you help me?

**Comment by azakhary** [comment]
if you can get the engine, you can fetch system from the engine. Is that an option?

**Comment by azakhary** [comment]
You can somehow fetch the sceneLoader which should not be a problem, then get engine from it, then call getSystem on it, then call the method.

**Comment by skusku** [comment]
I would need the `SceneLoader` in `CompositeComponentFactory`.
`CompositeComponentFactory` is instantiated in `EntityFactory` and
`EntityFactory` is insantiated in `SceneLoader`

I could send a reference to `Engine` over `EntityFactory `to `CompositeComponentFactory` just in order to call a `engine.getSystem(CompositeSystem.class).recalculateSize(Entity entity)` but I feel like that would result in very obfuscated code.

My suggestion is to 
- either have a static helper class ( a bit like EntityUtils ) 

- or to have a helper interface like:
```
public interface SystemRetriever{
   <T extends EntitySystem> T getSystem(Class<T> systemType);
}
```

make SceneLoader implement that interface and override the function with 
```
<T extends EntitySystem> T getSystem(Class<T> systemType)
{
   return engine.getSystem(systemType);
}
```

So that only that interface is passed around instead of SceneLoader, giving the code more readability.

What do you think? If I made such an interface, in what package would I put it? Or if I made a static class, what package would I put that into? If I made the static class, can you think of functions that would better fit such a place than where they are right now?

Hope I'm not annoying you, I just want to make things right :)

Have a nice weekend!!

**Comment by azakhary** [comment]
Thanks, this looks, great, I also did some changes on top and merged.

**Pull request merged**
