### PR TITLE
fixed start crash on linux

### PR DESCRIPTION
**Pull request by PkayJava**

### CODE REVIEW

**Comment by azakhary** [comment]
Thanks! Will pull this in 3 hours when I get to my PC.

**Comment by azakhary** [comment]
Have you made commit for textures folder? it seems like you pushed the resulting pack, but not the source images list. 

Here is how it usually works.
You add image to textures folder and commit it. you a run the app, and on start it re-generates the pack if textures folder has changed.

I would even suggest to add assets/atlas/uskin.json and uskin.atlas to .gitignore file
As there is no reason to keep them in the repo.

**Comment by azakhary** [comment]
if you just commit textures folder, I'll do the rest.

**Comment by PkayJava** [comment]
not yet,

icon-arrow-left.png
icon-arrow-right.png
icon-folder.png
icon-folder-parent.png
icon-drive.png
color-picker-selector-vertical.png
color-picker-selector-horizontal.png
color-picker-cross.png
color-picker-bar-selector.png
alpha-bar-25px-shifted.png
alpha-bar-25px.png
alpha-bar-10px.png

**Comment by azakhary** [comment]
Btw, previous merge with style changes does not work on windows. I am reverting back till we figure it out.

**Comment by azakhary** [comment]
I just pushed my changes including the gitignore change. So this pr now has conflicts that had to be resolved. (temporary removed FileChooser and ColorPicker styles from json) as for some reason it was giving error. Should vis-ui version be changed?

**Comment by PkayJava** [comment]
Yesh VisUI style has changed, just note, if you update VisUI to next version, there will be an error with FileChooser and ColorPicker

**Comment by azakhary** [comment]
Current version that we load is visuiVersion = '0.7.6' so json has to work with that.

**Pull request closed without merging**
