### PR TITLE
Fix cursor png bg color issue on linux

### PR DESCRIPTION
**Pull request by rcdvl**
Command used to fix issue #338 :
mogrify -background Black -alpha Background -define png:format=png32 *.png

(ran in the assets/cursors dir)

### CODE REVIEW

**Comment by rcdvl** [comment]
Please test this on Windows to check if all the cursors are ok

**Comment by azakhary** [comment]
Will test on windows and merge if all is good. 
Could you elaborate a bit more on what does this do exactly to the PNG's?

**Comment by rcdvl** [comment]
Sure. I tried to look for issues in the cursor code, but haven't found anything wrong, so I thought it might be an issue with the image. 
The problem was that the transparent pixels of the image were somehow storing some garbage (see http://www.imagemagick.org/discourse-server/viewtopic.php?t=13746), so this command is used in all images to keep the pixels transparent, but reseting their color to black. 
Don't ask me why it wasn't working because I have no idea... Might be something on cursor image blending

**Comment by azakhary** [comment]
Tested. Looks good on windows as well.

**Pull request merged**
