### PR TITLE
Add more event test

### PR DESCRIPTION
**Pull request by htynkn**
I add more test and I notice that seems coveralls didn't works well.
it says coverage is zero?! I run jacocoTestReport in my local, it should be 4%

In this RP, I adjust the test folder structure to put some test resource. I think we should clean up our project layout. I create another issue for that #245.

### CODE REVIEW

**Comment by azakhary** [comment]
Dude you are incredible :D I'll check this a bit later

**Comment by htynkn** [comment]
hmm... I think I know the reason. in travis, there is a error 
```
java.lang.UnsatisfiedLinkError: /tmp/libgdxtravis/7fcdd2ee/libjglfw64.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /tmp/libgdxtravis/7fcdd2ee/libjglfw64.so)
```
and for libgdx's logic, if there is a error, libgdx will call `System.exit(0)`.

so no matter how many test we create, it will never really run in travis....

**Comment by htynkn** [comment]
How terrible... find some way to update GLIBC or run test in docker...

**Comment by azakhary** [comment]
Ow. I see. I'll research on that too.

**Comment by azakhary** [comment]
So, should I merge this, or yet wait?

**Comment by htynkn** [comment]
yeah, please merge.

**Pull request merged**
