### PR TITLE
Tool tips for tool box

### PR DESCRIPTION
**Pull request by SpookyMachine**
Added tool tips in tool box UI part. Not the cleanest solution,  but i didn't want to refactor to much code for simple improvement. 

And i could use some help with setting back ground in tool tip. I modified uiskin.json and uiskin.atlas (didin't commint them), to read the tooltip-bg, but still it is mess. 
badbg

### CODE REVIEW

**Comment by azakhary** [comment]
I'll test this today.

**Comment by SpookyMachine** [comment]
Any update on testing?

**Comment by azakhary** [comment]
It works good, and tested well. The only thing here is, the correct String, and the style name. Why do you not commit the style? Do you want me to suggest the other? Let me know how to proceed with the style and the strings. As for the rest, implementation is correct.

**Comment by SpookyMachine** [comment]
Maybe i should have been more specific about my problem, then i said i could load the uiskin.json what i had in mind that i could load it without errors, but the background color is still the mess, which is shown in first comment. So to be exact, the problem is i could not get the skin loading working for the toolbar from the uiskin.json so the back ground would be black.

**Pull request closed without merging**
