### PR TITLE
Label properties change translation to command

### PR DESCRIPTION
**Pull request by kutoman**
- Enhancement: label text changes applied to canvas item instantly
- label properties changes now undo-/redoable

is related to #172 

Note: seems to be working properly. I'm not sure if you would do implement it in a better pattern.

### CODE REVIEW

**Comment by azakhary** [comment]
Sorry haven't merged yet, this one is a bit big, I have to check it myself, and was busy last 2 days. will do tomorrow! Meanwhile I was curious if changing translateViewToItemData method was the necessary? wasn't there a way to avoid that? can you please tell more on that.

**Comment by kutoman** [comment]
I couldn't figure out a more intuitive way, but there might be one. I first tried to override the *handleNotification* method in *UILabelItemPropertiesMediator* but I noticed that unfortunately that overridden method is not called by the BaseObserver registered by CoreView (sounds strange). Even though that method's reference is registered here (java 8 seems to ignore polymorphism here?): ```new BaseObserver(mediator::handleNotification, mediator);```
Hence, I solved it that way.

**Comment by azakhary** [comment]
generally translateObservableDataToView is intended to do what it's name says , thus it cannot take any parameters, as it only should work with observable. I am not sure what exactly that solved? I understand this thing is very similar to what I do with moving items around, and that worked without modifying that method.

Even more, the panel and it's mediator should not care about anything related to custom data, or previous data. that's the job of command. Here is how I suggest doing it.


1) Mediators and all stuff reverts back, there is no need to change that drastically.
2) LABEL_TEXT_CHAR_TYPED should not call for transform item to data view or whatever, it should just call a separate method in mediator, to just update the text nothing more. 
3) in mediator "on register" we remember initial text.
4) in transform view to data which is called when focus is out or enter is pressed. we call the command, pass the initial text in payload as it was recorded onRegister, and pass new text.


Makes sense?

**Comment by kutoman** [comment]
actually I was aware of that semantics you mentioned and I really wanted to avoid changing signatures, but I couldn't manage to do so when it comes to *2)*. I'm curious how you would catch that event (I tried to catch it by handleNotification in the UILabelItemPropertiesMediator, but it didn't work as explained). I think the item movement case is a bit different (because the items movement payload was built right after input events are received), as in our case we have a mediation (sending update events) from a properties view to a properties mediator.

**Comment by azakhary** [comment]
it will be catched by handle notification if only it is listed in public String[] listNotificationInterests() 
Check out for example UIBasicItemPropertiesMediator to see how it works. Mediator first declares notifications it want's to listen to. then it get's them via handleNotifiaction.

**Comment by kutoman** [comment]
I did put that certain event in the array of String[] listNotificationInterests() before but it didn't work. I mean the overridden handleNotification method does not get called. That's what I was trying to explain.

**Comment by kutoman** [comment]
ah wait, I'm so sorry... I now know why it didn't work. I recently retried and it worked...

**Comment by kutoman** [comment]
my bad, it was because I didn't use the text tool properly. I mentioned earlier that I couldn't see all the label properties (afterwards you told me to scroll in the properties box :) ). So I falsely repicked the text tool and then edited the properties. But those properties are not linked to to the label item I created earlier :(... so I falsely thought that polymorphism didn't work since the mediator was not linked to the new properties view anymore and so handleNotification does not get called naturally :D ).. 
ok, I will fix that

**Comment by kutoman** [comment]
hope it's ok now :)

**Comment by kutoman** [comment]
to avoid the confusion I had earlier I suggest to hide the Label properties section until a new label item is created on canvas

**Comment by azakhary** [comment]
Looks awesome!

**Pull request merged**
