### PR TITLE
Fix resolution removal #252

### PR DESCRIPTION
**Pull request by saltares**

### CODE REVIEW

**Comment by saltares** [comment]
I'm not too convinced whether this is the correct thing or not to do. Please check the branch out and test.

**Comment by azakhary** [comment]
Will do test first, this does re-load project, which in turn should also kick-start chain of notification that could possibly also lead to select box update or similar, will need to check the flow first.

**Comment by azakhary** [comment]
This fix was not working due to ResolutionEntryVO not having equals method override, thus removing from array using false argument was not working. I have just pushed changes to the runtime to ensure equals is overridden. It seems to be working well now, and fix is valid, so I am merging.

**Comment by saltares** [comment]
I was overriding equals on the ResolutionEntryVO... maybe I messed up when
pushing...

On 26 October 2015 at 10:46, Avetis <notifications@github.com> wrote:

> Merged #283 <https://github.com/UnderwaterApps/overlap2d/pull/283>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UnderwaterApps/overlap2d/pull/283#event-445374039>.
>



-- 
David Saltares Márquez

Software Developer
http://saltares.com

**Comment by azakhary** [comment]
Oh that's okay, I can imagine how this happened. ResolutionEntryVO is actually in the runtime not the editor, and runtime is in separate repo - https://github.com/UnderwaterApps/overlap2d-runtime-libgdx
That's why this push did not have it.

**Comment by saltares** [comment]
There you go, cheers, will keep that in mind.

On 26 October 2015 at 16:32, Avetis <notifications@github.com> wrote:

> Oh that's okay, I can imagine how this happened. ResolutionEntryVO is
> actually in the runtime not the editor, and runtime is in separate repo -
> https://github.com/UnderwaterApps/overlap2d-runtime-libgdx
> That's why this push did not have it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UnderwaterApps/overlap2d/pull/283#issuecomment-151198826>
> .
>



-- 
David Saltares Márquez

Software Developer
http://saltares.com

**Pull request merged**
