### PR TITLE
Remove stroke in all used fonts

### PR DESCRIPTION
**Pull request by nikoliazekter**
It looks so much better now. However I would like to remove black stroke from some other UI elements, especially textfields and checkboxes.
Also I think making menu font color a bit brighter would make font more readable and less blurred. Well, I just tried it and complete white is very good.

### CODE REVIEW

**Comment by nikoliazekter** [comment]
Is it going to be merged?

**Comment by azakhary** [comment]
I need to show this to our UI guy, he did put this strokes there for some reason, and we need his opinion first if you do not mind. That can take some time.

**Comment by nikoliazekter** [comment]
Sure, I jut thought that you're the one who handles UI.

**Comment by azakhary** [comment]
Okay, we tool a look. It's a bit complicated. I agree that our stroke is not as good as say, stroke in Photoshop. But, when you remove the stroke completely it becomes "blurred" and less sharp which in my opinion looks worse. The only case when removing stroke felt good is the "disabled menu items" maybe just make that change for that class only?

I know it's kind of a meter of taste here. So maybe a bit frustrating, but yeah, I am not sure how should we handle the "visual" parts like that in guthubs :)

**Comment by nikoliazekter** [comment]
Did you try setting the font color to white? It makes it much clearer and I guess ok enough.

**Comment by azakhary** [comment]
I did, I think we further debate this here: http://overlap2d.com/forums/topic/terrible-looking-font/

**Pull request closed without merging**
