### PR TITLE
Editor part of the fix - see issue 345

### PR DESCRIPTION
**Pull request by skusku**
This fix consists of 2 parts - check overlap2d-libgdx-runtime for the other part.

### CODE REVIEW

**Comment by azakhary** [comment]
The travis check fails with:
/root/overlap2d/overlap2d/src/com/uwsoft/editor/view/ui/properties/panels/UIPolygonComponentPropertiesMediator.java:108: error: method makeRectangle in class PolygonComponent cannot be applied to given types;
            polygonComponent.makeRectangle( dimensionsComponent.boundBox.x, dimensionsComponent.boundBox.y, dimensionsComponent.boundBox.width, dimensionsComponent.boundBox.height);

could you see what it can be?

**Comment by skusku** [comment]
Yes, the fix consists of two fixes which depend on each other.
 We need the new function:

makeRectangle(float, float, float, float) in PolygonComponent (which is part of libgdx-runtime)

For this to work - which is included in the libgdx-runtime pull request

**Comment by azakhary** [comment]
Got it, merged, let's see if it'll pass check now

**Comment by skusku** [comment]
What's that coverage thing? Is it something bad?

**Comment by azakhary** [comment]
We're good. Coverage is just the percent of methods that have unit tests for them, because you just added new method without a unit test, coverage percent dropped. That's no biggie, I'll add a test later. This one is good to go.

**Comment by skusku** [comment]
Awesome! :+1:

**Pull request merged**
