### PR TITLE
Creating Unit Tests

### LINKED ISSUE #231: Creating Unit Tests

### PR DESCRIPTION
**Pull request by htynkn**
Hi azakhary,

I create some test and add a travis config.

For travis part, could you go to travis website and turn it on?

If you have time, I suggest to have a look at [coveralls](https://coveralls.io/). This tool is free for open source project and can help us to trace the unit test coverage change for whole project.

Take this project as an example, it's a java project with travis and coveralls.
[https://github.com/kt3k/coveralls-gradle-plugin](https://github.com/kt3k/coveralls-gradle-plugin)

Thanks.

Fix #231

### CODE REVIEW

**Comment by azakhary** [comment]
Testing this right now, should not be long till merge

**Comment by azakhary** [comment]
Travis website is not loading o_O

**Comment by azakhary** [comment]
Okay merged this and travis started building. Although it did output build failed.

**Comment by azakhary** [comment]
oh wait no it passed.

**Comment by htynkn** [comment]
yeah, it passed.

Could you have a look at coveralls? It can help us to trace the unit test coverage change.
I guess what need do is using a gradle plugin and adding coveralls auth key in travis.

**Comment by azakhary** [comment]
I looked at coveralls, I am sorry I am a bit new to this. so there are some keys. but it says not to put them publicly so I am not sure to what config what should be put o_O Can you help me out with the setup?

**Comment by azakhary** [comment]
Another question I had, we are asserting in unit tests version number, is that right thing to do? when version changes we have to change it from test as well, isn't it better to retrieve it from somewhere? or what is the common practice for that?

**Comment by azakhary** [comment]
Should I only change travis.yml and build.gradle as per plugin readme? or there is something else?

**Comment by azakhary** [comment]
at this point I can't understand if we should have .coveralls.yml or not. Take a look at our readme now. it shows coverage: uncknown

**Comment by htynkn** [comment]
yeah, it's not common practice.

We should change it to retrive version from somewhere(for example, build.gradle file) or just delete it. I create that test just because it looks easy to create test....

About coveralls, I check the travis log, looks like there is an error `error:true, message:Couldn't find a repository matching this job`. I even see this error before, so I'm not sure .coverall.yml file can sort it out.




发件人：Avetis <notifications@github.com>
发送时间：2015-09-05 15:22
主题：Re: [overlap2d] Creating Unit Tests (#232)
收件人："UnderwaterApps/overlap2d"<overlap2d@noreply.github.com>
抄送："Huang YunKun"<htynkn@gmail.com>

Another question I had, we are asserting in unit tests version number, is that right thing to do? when version changes we have to change it from test as well, isn't it better to retrieve it from somewhere? or what is the common practice for that?

**Comment by htynkn** [comment]
Cool! I see it works after you change the service_name.

Only 1.96% coverage now, I will continue to add unit test once I have time.

Thanks very much azakhary.

**Comment by azakhary** [comment]
Awesome, we're up and running. Thank you so much for helping out with this. I'll try to add some tests as well as we move forward. Maybe we can discuss in issue tracker what parts are most vulnerable to add tests first.

**Pull request merged**
