### PR TITLE
+adds zoom, X and Y labels over sandbox

### PR DESCRIPTION
**Pull request by AlbertoCejas**
As a way to introduce me to the code, I decide to add a simple zoom indicator text over the Sandbox UI, keeping the same structure than before.
This zoom indicator will only appear if there is a project opened and makes things clearer to the user.

It looks as follows:

pull_request

### CODE REVIEW

**Comment by AlbertoCejas** [comment]
I have also added X and Y text labels so the user can know the current cursor coordinate

**Comment by azakhary** [comment]
Hi, this looks good! I'll test in on monday, before merging. But I have to say that, I will have to rewrite it a little bit later, as we are adding a "status" bar at the bottom, so I will put it down there when it is ready. Thanks!

**Comment by AlbertoCejas** [comment]
Perfect! Is there any public roadmap where you write required features, what are you working on, etc so people can add it to the editor without making double efforts?
Thanks in advance!

**Comment by azakhary** [comment]
not yet, but there should be.
This one is not a double effort though, I will just change the location of labels.

**Comment by AlbertoCejas** [comment]
Regarding this PR, I didnt refer to have done double effort on this specific feature but I'd like to contribute and maybe it's more necessary to help in some specific aspects than just figuring out what to do. Can you guide me on what to do? maybe we can contact by any other source than these PR messages.

**Comment by azakhary** [comment]
I was thinking to create a public roadmap, and a system for us to figure this type of things out, but honestly I think this would be more productive to do after I merge things I was working on, on  my local branch. That is probably in 2 weeks. Meanwhile till we get there - you are most welcome to 1) check out branch called mvc on my local fork, to see how structure and all is going to be changed. Also you are always welcome to email be at azakhary [at] underwaterapps.com

**Comment by azakhary** [comment]
Now that new overlap2d architecture is out. I will try to see how can I merge your work into this new version. I am sorry for this kind of HUGE delay :))

**Comment by azakhary** [comment]
Okay so I put it in back in new version in form of both - rulers and guides show your cursor position and current zoom is displayed in zoom panel.

**Comment by azakhary** [comment]
As for public roadmap - check this out: http://overlap2d.com/contributing-to-overlap2d-editor/

**Pull request closed without merging**
