### PR TITLE
Restricted mouse move (vertically, horizontally)

### PR DESCRIPTION
**Pull request by kutoman**
Note: I reverted the "local config change". Should I create a new pull request for that one? I still think it's very useful during development (instead of having to choose the project via mouse everytime when restarting overlap2d, we just need to determine the directory of a 'dummy' project locally in a config file. It won't harm those who don't need it)

### CODE REVIEW

**Comment by azakhary** [comment]
Sorry for delay, will check this out tomorrow morning. too busy :)

**Comment by azakhary** [comment]
Hi, I am currently testing this, and when I say, press control and move object up/down, it sometimes jumps left/right  is it a planned behavior or bug?

**Comment by azakhary** [comment]
Btw, pretty neat feature, awesome

**Comment by kutoman** [comment]
:) yeah it's a pretty mandatory feature when it comes to moving around graphical objects via mouse in an editor.
concerning the jumping thing. if you mean that the jump happens in a short distance to the mouse drage starting point, yes it is. I also double checked that feature in inkscape where we have the same case. It's a natural behavior due to the algorithm (as soon as delta x or delta y is higher than the other coordinate the move direction changes immediately)

**Comment by azakhary** [comment]
I was thinking the logic should be - if  I started moving up down, then it is always up down unless I stop and start again. same with left+right. so once you choose direction you can't change it.

**Comment by kutoman** [comment]
hmm maybe that's better. I'm curious why in inkscape it's not like that. I don't know what's the case in other editors, perhaps someone here does know?

**Comment by azakhary** [comment]
In Photoshop, and all adobe products.
It is Shift instead of Control, and it is the way I described it (once direction is chosen you do not change it) I also think Adobe products are a lot more popular then inkscape and many people are used to that. So I vote for making it the adobe way.

**Comment by kutoman** [comment]
ok, makes sense actually. I will try to implement it today (should be just a few lines of code to be changed)

**Comment by azakhary** [comment]
Yep, I am all for shift.

Thank you!

**Comment by kutoman** [comment]
There is a little problem with the shift key. It's the key to add/remove items to/from a selection. Thus there is a conflict which is annoying. What would you suggest?

**Comment by azakhary** [comment]
yeah but I am not sure this should be a problem, you should not do things on shift pres, it's just when dragging you should do a check if "isKeyPressed on gdx.input" it should work just fine.

**Comment by azakhary** [comment]
there would not be a use case where this 2 conflict. plus in Adobe Flash they do have shift for select deselect, and shift for that move , and it works together

**Comment by kutoman** [comment]
at least it does in my implementation :D the dragging gets aborted. Let me see how to avoid that..

**Comment by azakhary** [comment]
The solution in flash is, that it unselects on shift when mouse is UP, not mouse is DOWN, thus it happens after the drag complete.

**Comment by kutoman** [comment]
and when dragging with shift the selection group shouldn't get affected right?

**Comment by azakhary** [comment]
yep

**Comment by kutoman** [comment]
I hope it's correct now

**Comment by azakhary** [comment]
Seems to be working fine, thanks!

**Pull request merged**
