### PR TITLE
Wrong location when creating new project #266

### PR DESCRIPTION
**Pull request by choxxy**
This really bothered me, this what I had in mind.

### CODE REVIEW

**Comment by azakhary** [comment]
Hi, there is something off with the PR - check the changed files, can you please fix that?

**Comment by choxxy** [comment]
Working on it

**Comment by azakhary** [comment]
I do remember fixing wrong location though several days ago. I am curious if this is new issue? re-fix of old one, or I did mess up something and this is fix for that one :D we'll see.

**Comment by choxxy** [comment]
Had done the fix sometime ago, but didn't create  a pull request. If you have already fixed it I think you can discard this pr.

**Comment by azakhary** [comment]
Okay, I checked, and it's my bad, I did fix it, but somehow did not make PR for it, so fix is not here. So yeah. I'll do PR first thing in the morning, sorry for confusion. it's this issue: https://github.com/UnderwaterApps/overlap2d/issues/266

**Comment by azakhary** [comment]
I changed more of the structure, so I am going to merge #285 instead. Reason is previously it was work-space based, and then we changed it, but old code remained, so it was a mess.

**Pull request closed without merging**
