### PR TITLE
add default arial font

### PR DESCRIPTION
**Pull request by PkayJava**

### CODE REVIEW

**Comment by azakhary** [comment]
this code does not work. it trie to copy "freetypefonts"  directory. but it does not exist.  

Furthermore, i advice on creating an issue first before doing a PR, so it can be discussed by community before the coding starts. Because my advice here is that we do not bundle fonts with the app, but allow people drag/drop ttf's to the new drag and drop window.

**Comment by PkayJava** [comment]
there are fonts inside freetypefonts, when I first start overlap2d, create new project, and choose Text Tool, click click on scene, it throw an exception (because of there is no fonts)

**Comment by azakhary** [comment]
Ah, got it. Sorry. But I think we should approach this issue differently. let me explain.

The system is made so that it will scan your machine for already installed fonts, during the first run. And then add them to the MAP with paths. So that when you choose text tool. that fonts will appear in the list and not exception will happen.

Currently it works perfectly on windows. So here is what needs to be done:

1) Text tool needs to be modified that if list is empty - don't make label. to avoid NullPointer
2) Font scanning should be modified to work also on Linux. it is currently looking in folder: 
result[0] = System.getProperty("user.home")+File.separator + ".fonts"; 
is this the correct directory? Where are fonts usually on Linux? if it's somewhere else, path needs to be changed.  (FontManager.java line: 72)
3) If person does not have ANY fonts installed on their system. We should give them ability to import fonts into their overlap2d project. That should be done in ImportDialogMediator and ImportUtils files. This even have TTF part commented out, and if it's implemented, user will also be able to import his own fonts.
4) Finally, I think we should check if freefonttypes directory is used anywhere? if it is not, I think it is just there from old versions, and should be removed. I see no point in boundling Arial font with the editor, because any system has at least some font already installed by default, and FontManager is supposed to find it.

**Comment by PkayJava** [comment]
when program ran into case 3) and user have not yet import some fonts, could we provide some default fonts which are embedded in the jars file itself ?

and if user import more TTF, when program should also look for from the project asset folder itself.

What do you think ?

**Comment by azakhary** [comment]
I am not big fan of idea to provide default fonts. why should we choose one font over the other? Even more, why does user even need arial font? If he is making an actual game arial font is of no use, and if he is just playing around, then there is no need to provide entire font for just playing around. Obviously when someone started making a game, they have prepared fonts first if they plan to use fonts. And they should be able to import them. When they first try to drop the text on scene, it should say "please import fonts" Also it is important to mention that this is a very rare case. Normally a person will use a comfortable windows machine with tons of fonts already isntalled. Even linux machine I am sure has some fonts already there, we just have to know where it is and fix in part 2. Linux probably already has that "arial font" bundled somewhere, or some alternative.


As for second point, it is valid, it should also look in assets folder and put that fonts to the list.

**Comment by azakhary** [comment]
I am closing this pull request till the other one, so we have clear list :)

**Pull request closed without merging**
