### PR TITLE
extended alignment tool box

### PR DESCRIPTION
**Pull request by kutoman**
- added edge alignment (left, right, top, bottom); Note: buttons need to be modified visually
- refactored older code (and fixed some alignment bugs)

### CODE REVIEW

**Comment by azakhary** [comment]
hmm.. I am not really sure what Icons to put there, the logic of this alignment is weird. Is there something like that in any other software?

**Comment by kutoman** [comment]
rect4157

inkscape does provide such alignment (I marked the respective icons)

**Comment by azakhary** [comment]
Git it.. well it will take time to make this icon :D will see if I can manage tomorrow.

**Comment by kutoman** [comment]
I also could try to make some (it might fit overlap2d's style) if you want :).

**Comment by azakhary** [comment]
If you give me the icon, I will put it in atlas.

**Comment by kutoman** [comment]
here you are:
alignedgeicon
alignedgeiconchecked

**Comment by azakhary** [comment]
Okay, icons are in - merged.

**Pull request merged**
