### PR TITLE
Tooltip messages

### PR DESCRIPTION
**Pull request by AlexGladin**
Tooltip messages for icons in UiToolBox

### CODE REVIEW

**Comment by azakhary** [comment]
Hmm. I cannot merge this, why did you delete the gradle settings?

**Comment by AlexGladin** [comment]
"Freetype" library throw error, when generate new BitmapFont

**Comment by azakhary** [comment]
but why delete gradle settings?

**Comment by azakhary** [comment]
I see that you purged entire settings files, all of them, as well as added a new font, this should not be necessary for implementation.

**Comment by AlexGladin** [comment]
I'm forgot add gradle settings(
New fnt file need for normal displaying font's in application.

**Comment by azakhary** [comment]
why don't you want to use the existing font that is used in buttons skin?

**Comment by AlexGladin** [comment]
Freetype throw error when create BitmapFont from ttf file.

**Comment by azakhary** [comment]
you do not need to create it from ttf.
there is already loaded fnt file from "https://github.com/UnderwaterApps/overlap2d/blob/master/assets/fonts/arial.fnt"

**Comment by azakhary** [comment]
EditorResourcemanager is working fine it requires no change, I am not sure why is it throwing error on your machine.

**Comment by AlexGladin** [comment]
Size of this font equals 20
There error, most likely error in new version of library

**Comment by azakhary** [comment]
I'll try to look into this today, see what can cause this error.

**Pull request closed without merging**
