### PR TITLE
Reduced selection move (horizontal/vertical) by mouse + Support of local config file

### PR DESCRIPTION
**Pull request by kutoman**
-> the reduced selection move is enabled by pressing/holding the 'control' button.
-> the local config file (to be managed at "local/config.properties") enables to determine a "projectDir" of a overlap2d project which should be loaded at start-up (saves some time during development). The config file can also be omitted of course.

### CODE REVIEW

**Comment by azakhary** [comment]
Hi

My suggestion will be to keep separate features in separate pull requests. For example in this case, the selection move amount is something I would want to merge, but the config file part is a bit debatable, because as far as I know in issue #19 @eumario was already working on something similar.

So can you devide this into 2 pull request, and also if @eumario can comment on this, so we will know if this are different features or the same?

**Comment by kutoman** [comment]
oh sorry, you're right. How to divide it the best way (have never done it before)?

**Comment by eumario** [comment]
@azakhary @kutoman,
I am working on a different approach to the "local" config, instead of having that as it is, I'm working with LibGDX Prefs, so that we can have them stored in a system wide local folder for us automatically.  Instead of having the last project opened when you start up, you'll get an Sub-menu entry in File, that gives you x amount of last projects you have worked on.  So, I would call this, an incompatible feature with the one I'm working on currently, as for the local config part.  The other part, with control, has nothing to do with what I'm working on, so you can leave that in, but remove the local configuration stuff, as we'll have a Global Configuration Manager to manage all settings we will want in the future.

**Comment by azakhary** [comment]
@kutoman can you create another branch from master and add there just the control part, and make another pull request? I am closing this one.

**Pull request closed without merging**
