### PR TITLE
ignore recent project which is not existed (e953e21)

### PR DESCRIPTION
**Pull request by PkayJava**
pull request (e953e21)

### CODE REVIEW

**Comment by azakhary** [comment]
Could you please base your branch on latest master so that only PreferencesManager.java currently also stuff from your previous pr comes as well, which should not. Thanks.

**Comment by PkayJava** [comment]
I am not sure how to base my branch on latest master, I just delete my forked, and re-fork again, but this is not a good solution, It would be nice if you teach me how to base my branch on latest master

**Comment by azakhary** [comment]
so the best way to do it is: whenever you want to start doing something:
1) go to your master branch (git checkout master)
2) make sure it has all the latest data (git pull upstream master) (where upstream is a remote you added earlier that points to official repo)
3) now that you are on latest master do: git checkout -b new_branch_name
4) this will be a branch based on latest master, so you can just code your stuff now
5) do some git commits
6) push it to your origin: git push origin new_branch_name
7) do pull reuqest from your new_branch_name on origin to official repo master.

**Comment by PkayJava** [comment]
i got error on step 2) git pull upstream master

fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by azakhary** [comment]
check this: where upstream is a remote you added earlier that points to official repo

What I meant here is you first need to have upstream added.
to do that write (this is done just once):

git remote add upstream https://github.com/UnderwaterApps/overlap2d.git

Read more here:
https://help.github.com/articles/adding-a-remote/

**Pull request closed without merging**
